// *****************************************************************************
// bool grammar
// *****************************************************************************
//
// depends on: nothing
// *****************************************************************************

<bool_var> ::= 'b'

<bool_assign> ::= <bool_var>' = '<bool>

<bool_var_const> ::= <bool_var> | <bool_const>

<bool> ::= <bool_var> | <bool_const>
         | <bool_pre> <bool_var_const>
         | '(' <bool_var_const> <bool_op> <bool_var_const> ')'

<bool_op> ::= 'and' | 'or'
<bool_pre> ::= 'not'

<bool_const> ::= 'True' | 'False'
