// *****************************************************************************
// bool grammar
// *****************************************************************************
//
// depends on: nothing
// *****************************************************************************

<bool_var> ::= 'x'

<bool_assign> ::= <bool_var>' = '<bool>

<bool> ::= <bool_var> | <bool_const>
         | <bool_pre><bool>
         | '(' <bool> <bool_op> <bool> ')'

<bool_op> ::= 'and' | 'or'
<bool_pre> ::= 'not'

<bool_const> ::= 'True' | 'False'
