// *****************************************************************************
// list grammar for string list
// *****************************************************************************
//
// depends on: string (string, string_var)
// return: list of int
//         string (optional)
//         bool (optional)
// *****************************************************************************

<list_string_var> ::= 'listvar_string'

<list_string_assign> ::= <list_string_var>' = '<list_string>

<list_string> ::= <list_string_var> | <list_string_slice>
<list_string_slice> ::= <list>'['<int>':'<int>']' | <list>'[:'<int>']' | <list>'['<int>':]'

<getListIndexCall_string> ::= 'getIndexStringList('<list_string>', '<int>')'
<setListIndexToCall_string> ::= 'setListIndexTo('<list_string>', '<int>', '<string>')'

// Add to

<call> ::= <list_string_var>'.append('<int>')'
         | <list_string_var>'.insert('<int>','<string>')'
         | <deleteListItemCall>
         | <setListIndexToCall>

<for> ::= <loop-header>'for forCounter% in '<list_string><loop-block>
        | <loop-header>'for '<string_var>' in '<list_string><loop-block>

// Generic for all

<in_list_comp_op> ::= 'in'|'not in'
<deleteListItemCall> ::= 'deleteListItem('<list>', '<int>')'

// Return string

<ret_string> ::= <getListIndexCall_string>

// Return bool

<ret_bool> ::= <string> <in_list_comp_op> <list_string>

// *****************************************************************************
// Helper Code
def getIndexStringList(curList, index):
  if not curList:
    return str()
  return curList[index % len(curList)]
