// *****************************************************************************
// bool grammar
// *****************************************************************************

<char_var> ::= // placholder for variable names

<assign> ::= <char_assign>
<char_assign> ::= <char_var>' = '<char>

<char> ::= <char_var> | "'"<char_literal>"'"

<char_literal> ::= '\\n' | '\\t' | ' ' | '!' | '"' | '#' | '$' | '%' | '&' | "\\'" | '(' | ')' | '*' | '+' | ',' | '-' | '.' | '/' | '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | ':' | ';' | '<' | '=' | '>' | '?' | '@' | 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' | '[' | '\\\\' | ']' | '^' | '_' | '`' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' | '{' | '|' | '}'

<string> ::= <char>

<bool> ::= <char>'.isdigit()' | <char>'.isspace()' | <char>'.isalpha()' | '('<char>' == '<char>')'

<int> ::= 'ord('<char>')'
