// *****************************************************************************
// int grammar
// *****************************************************************************
//
// return: bool (optional)
// *****************************************************************************

<int_var> ::= 'i'

<int_assign> ::= <int_var> '=' <int> | <int_var> <arith_assign> <int>

<int_var_const> ::= <int_var> | <int_const>

<int> ::= <int_var> | <int_const>
        | <arith_prefix><int_var_const>
        | '(' <int_var_const> <arith_ops> <int_var_const> ')'
        | <int_arith_ops_protected>'('<int_var_const>','<int_var_const>')'
        | 'min('<int_var_const>', '<int_var_const>')'
        | 'max('<int_var_const>', '<int_var_const>')'
        | 'abs('<int_var_const>')'

// to avoid problems with leading zeros in python int
<int_const> ::= 'int('<number>'.0)'
<number> ::= <num> | <num><num> | <num><num><num> | <num><num><num><num> | <num><num><num><num><num>
           | <num><num><num><num><num><num> | <num><num><num><num><num><num><num>
           | <num><num><num><num><num><num><num><num> | <num><num><num><num><num><num><num><num><num>
           | <num><num><num><num><num><num><num><num><num><num>
<num> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9

<arith_assign> ::= <arith_ops>'='
<arith_ops> ::= '+'|'-'|'*'
// ** raises ZeroDivision error when 'a = 0; a ** ~a'
// |'**'

<int_arith_ops_protected> ::= 'divInt' | 'mod'
<arith_prefix> ::= '+'|'-'
//|'~'

<comp_op> ::= '<'|'>'|'=='|'>='|'<='|'!='|'is'|'is not'

// Return bool

<ret_bool> ::= <int_var_const> <comp_op> <int_var_const>

// *****************************************************************************
// Helper Code
// *****************************************************************************

def div(nom, denom):
  if denom <= 0.00001:
    return nom
  else:
    return nom / denom


def divInt(nom, denom):
  if denom <= 0.00001:
    return nom
  else:
    return nom // denom


def mod(nom, denom):
  if denom <= 0.00001:
    return nom
  else:
    return nom % denom
