// *****************************************************************************
// Grammar containing the python structure
// *****************************************************************************
//
// depends on: int
//             bool
// *****************************************************************************

<predefined> ::= 'i = int()'
                 'b = bool()'
                 's = str()'
                 'f = float()'
                 'list_bool = []'
                 'list_int = []'
                 'list_float = []'
                 'list_string = []'
                 'res = int()'
                 <code>

<code> ::= <code><statement>'\n' | <statement>'\n'

<statement> ::= <simple_stmt> | <compound_stmt>
<simple_stmt> ::= <call> | <assign>
<compound_stmt> ::= <if> | <while> | <for>

<call> ::= //call statements

<assign> ::= // assign statements

<if> ::= <if-then> | <if-then><else>

<if-then> ::= 'if '<bool><block>
<else> ::= 'else'<block>

<block> ::= ':{:\n'<code>':}'


<while> ::= <loop-header>'while '<bool><loop-block>
<for> ::= // for statements depend on lists or use of range

<loop-header> ::= 'loopBreak% = 0\n'
// stop[0] is set by outer code to break immediately
<loop-block> ::=' :{:\n'<code>'\nif loopBreak% > loopBreakConst or stop[0]:{:\nbreak\n:}loopBreak% += 1\n:}'
